# Site settings
title: 에그로그 | 간호사의 근무 관리를 손쉽게
description: "에그로그 개발 기록"
url: "https://blog.egg-log.org"
author:
  name: "egg-log"
  email: "eggrock2023@gmail.com"
  url: "https://blog.egg-log.org"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins: [jekyll-paginate, jekyll-sitemap]
# gems:
#   - jekyll-paginate
#   - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# comment
disqus: egglog